spring.application.name=finapp-backend

spring.profiles.active=dev

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=bXlTdXBlclNlY3JldEtleUZvckZpbmFwcEFwcGxpY2F0aW9uVGhpc0lzQVNlY3JldEtleQ==
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
logging.level.com.finapp.service.BankPdfParser=DEBUG
logging.file.name=app.log
