spring.application.name=finapp-backend

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/finappdb?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=2002

# JWT Configuration
jwt.secret=bXlTdXBlclNlY3JldEtleUZvckZpbmFwcEFwcGxpY2F0aW9uVGhpc0lzQVNlY3JldEtleQ==
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
